export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const SELECT_CATEGORY_PART = 'SELECT_CATEGORY_PART';
export const COMPLETE_CATEGORY = 'COMPLETE_CATEGORY';

export const ADD_CATEGORY_PART = 'ADD_CATEGORY_PART';
export const REMOVE_CATEGORY_PART = 'REMOVE_CATEGORY_PART';
export const EDIT_NEXT_CATEGORY = 'EDIT_NEXT_CATEGORY';
export const EDIT_PREV_CATEGORY = 'EDIT_PREV_CATEGORY';

export const COMPLETE_STEP = 'COMPLETE_STEP';
export const UNDO_STEP = 'UNDO_STEP';

export const SAVE_DESCRIPTION = 'SAVE_DESCRIPTION';
export const LOAD_DESCRIPTION_SUCCESS = 'LOAD_DESCRIPTION_SUCCESS';

export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const REMOVE_MESSAGE_SUCCESS = 'REMOVE_MESSAGE_SUCCESS';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const GET_ID_SUCCESS = 'GET_ID_SUCCESS';

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const LOAD_PARTS_SUCCESS ='LOAD_PARTS_SUCCESS';
export const COMPLETE_CATEGORY_SUCCESS = 'COMPLETE_CATEGORY_SUCCESS';
export const COMPLETE_CATEGORY_FAILED = 'COMPLETE_CATEGORY_FAILED';

export const LOAD_STEPS_SUCCESS = 'LOAD_STEPS_SUCCESS';
export const COMPLETE_STEP_SUCCESS = 'COMPLETE_STEP_SUCCESS';
export const UNDO_STEP_SUCCESS = 'UNDO_STEP_SUCCESS';
